default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  database: rota151_development
test:
  <<: *default
  database: rota151_test
production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
  cache:
    <<: *primary_production
    database: rota151_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rota151_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rota151_production_cable
    migrations_paths: db/cable_migrate
