default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rota151_development
test:
  <<: *default
  database: rota151_test
production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: rota151_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rota151_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rota151_production_cable
    migrations_paths: db/cable_migrate
